### ISSUE TITLE
Add support for locks

### ISSUE THREAD

**Issue by andersbetner** [domwillcode/yale-smart-alarm-client#13]
I have the Yale Smart Living Hub and a Yale Doorman Lock.
I have run the Yale Smart Living IOS app through Charles Proxy (using socks), but I can't for the life of me get a packet capture of the apps communication.

My only Android device refuses to install the Yale App. (lenovo tab 4)
@domwillcode 
Would it be feasible if I created a login for you on my Yale account to get a capture of the lock communication? (If not just for the joy of being able to unlock a door in Sweden :)
I could add a pull request if I have a capture.

**Comment by mipe79** [comment]
I look in the source code and it looks like there are some kind of supportfor locks in client already?

https://github.com/domwillcode/yale-smart-alarm-client/blob/master/yalesmartalarmclient/client.py

 def get_locks_status(self):

YALE_LOCK_STATE_LOCKED = "locked"
YALE_LOCK_STATE_UNLOCKED = "unlocked"
YALE_LOCK_STATE_DOOR_OPEN = "dooropen"
YALE_LOCK_STATE_UNKNOWN = "unknown"

**Comment by anderselton** [comment]
I added support for locks in my fork. (https://github.com/anderselton/yale-client)

If you want to take the lock support into this project, the relevant parts is in this file https://github.com/anderselton/yale-client/blob/master/yaleclient/lock.py
(YaleDoorManAPI:open_lock and close_lock)

**Comment by laf** [comment]
Thanks for doing that @anderselton. It would be good if you could submit a pull request to this repo so that things don't split out too much especially as HA uses this one.

**Comment by domwillcode** [comment]
Ditto

**Comment by domwillcode** [comment]
Thanks @anderselton. It'd be great if you could submit a PR? Happy to push up a new version to pypi.

**Comment by anderselton** [comment]
I cant submit PR, dont have access.
I have a local branch now, with the changes more in line with how the client here is built.
