### ISSUE TITLE
Support for events history

### ISSUE THREAD

**Issue by supercrab** [domwillcode/yale-smart-alarm-client#15]
Hi

In the old Yale API you could retrieve all the events in the history using the endpoint 

https://www.yalehomesystem.co.uk/homeportal/api/panel/get_report_events/

Do you know what the new endpoint is?

Cheers
M

**Comment by gjohansson-ST** [comment]
In the last version use get_history()

**Comment by supercrab** [comment]
I looked in the code and found that the new web call is "yapi/api/event/report/?page_num=1&set_utc=1"
