### ISSUE TITLE
Trigger the Alarm using the API

### ISSUE THREAD

**Issue by diazwatson** [domwillcode/yale-smart-alarm-client#21]
Anyone know if is possible to trigger the Alarm using the API?
From where I can see it is a must specially if you want to use in HA automations to fire the alarm using non yale devices

Thanks

**Comment by qerim** [comment]
It's not yet possible in this client I believe. However I did notice Yale pushed an App update recently which has ability to trigger alarm:
https://yalehome.co.uk/news/2020-articles/yale-home-app-update-2020

**Comment by diazwatson** [comment]
That means there is a command in the API to trigger the alarm.
Now the question is how to know this command?
I am more than happy to contribute and update this client if someone points me in the right direction

**Comment by diazwatson** [comment]
The other thing I can think of is reverse engineer the Yale app to see what it does to trigger the alarm.
But that sounds like a crazy approach 🤔

**Comment by petheridge** [comment]
@diazwatson @domwillcode So I have been grabbing my IOS traffic with Burp proxy, I 'think' this is POST command to trigger the alarm. Only the second time I've grabbed anything with this, more than happy to share more if needed.

> POST /api/panel/panic HTTP/1.1
Host: mob.yalehomesystem.co.uk
Content-Length: 0
Connection: close
Accept: application/json
User-Agent: React Native OAuth2 Client v3.2.0
Authorization: Bearer vqIZ3ZE1v6KAxxxxxxxxxxxxxxxxPhSDlo
Accept-Language: en-gb
Accept-Encoding: gzip, deflate

For comparison this is the POST command I recorded for disarming the alarm:
> POST /yapi/api/panel/mode/ HTTP/1.1
Host: mob.yalehomesystem.co.uk
Content-Type: multipart/form-data; boundary=hh2bD6B9v-WTNjFWFkaq1IcxxxxxxxxxxxxxxxxxxxxDMpMoacQjz2vX.RRpPNwjf.1UaL
Accept-Encoding: gzip, deflate
Connection: close
Accept: */*
User-Agent: React Native OAuth2 Client v3.2.0
Authorization: Bearer vqIZ3ZE1vxxxxxxxxxxxxxxxRNPhSDlo
Content-Length: 329
Accept-Language: en-gb

--hh2bD6B9v-WTNjFWxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoacQjz2vX.RRpPNwjf.1UaL
content-disposition: form-data; name="area"

1
--hh2bD6B9v-WTNjFWxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxQjz2vX.RRpPNwjf.1UaL
content-disposition: form-data; name="mode"

disarm
--hh2bD6B9v-WTNjFxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxcQjz2vX.RRpPNwjf.1UaL--

**Comment by diazwatson** [comment]
Hi @petheridge this is very interesting. I tried to do something similar sniffing into the connections of my local network but could not get anything useful.

So, the endpoint in API to trigger the alarm seems be:

```
/api/panel/panic
```

I wonder if I can test this with something like postman, the only issue I see would be the generation on the bearer token

Has anybody tested this?

**Comment by diazwatson** [comment]
Thanks guys @qerim @petheridge 👍

**Comment by domwillcode** [comment]
New version up here with #23 : https://pypi.org/project/yalesmartalarmclient/0.3.0/

Thanks @diazwatson @qerim @petheridge!

**Comment by diazwatson** [comment]
Thanks @domwillcode 🙌

**Comment by diazwatson** [comment]
Hi @petheridge 

Do you know or can point me in the right direction on how to get the alarm status when this is triggered?
I have checked the `yapi/api/panel/mode` endpoint after triggered the panic button but the response does not offer anything useful.

It only offers information about whether the alarm is `disarm` , `home` or `arm`

However, if I look at the mobile app after triggering the alarm from the client I can clearly see a flashing red siren indicating the alarm has been triggered.

I believe there must be some sort of request to activate this in the mobile app.
