### ISSUE TITLE
Be able to know when the alarm is in triggered status

### ISSUE THREAD

**Issue by diazwatson** [domwillcode/yale-smart-alarm-client#24]
After [adding support to trigger the alarm](https://github.com/domwillcode/yale-smart-alarm-client/pull/23) (using the panic button recently added by Yale) I was thinking, another useful feature for the client would be to be able to tell when the alarm is in a triggered state.

Does anyone know if the Yale API currently provides this information?

**Comment by Lightroom-47** [comment]
Hi Diazwatson, just wondering if there has been any movement on this. Really keen to have this option. Thanks.
