### ISSUE TITLE
Panic button endpoint

### ISSUE THREAD

**Issue by Mr-Grover** [domwillcode/yale-smart-alarm-client#28]
Hello,

I have started testing adding the panic button to the HA integration and when I call trigger_panic_button() I get the follow error

`(requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mob.yalehomesystem.co.uk/yapi/yapi/o/token/)` 

Are we sure the "/api/panel/panic" endpoint works ?

Thanks !

**Comment by diazwatson** [comment]
Hi, it does work indeed. 
You can test calling the API yourself.

This is how I do in Postman

POST URL: 
```
https://mob.yalehomesystem.co.uk:6013/api/panel/panic
```

**Note:** Remember you going to need to pass your  Bearer Token previously generated

**Comment by Mr-Grover** [comment]
Thank you for the reply. It might of been something I did wrong in the HA code... But all the other calls work except this one Bit odd. I will have to come back to it. By the way I pinged you on discord last month if you still use that have a look :)

**Comment by diazwatson** [comment]
Sorry I completely missed that message in discord.
I am going to check now
