### ISSUE TITLE
Not Issue, how can I use it in Homeassistant?

### ISSUE THREAD

**Issue by Marmoulak** [domwillcode/yale-smart-alarm-client#43]
Hi
I am new in this. 
How can I use it in home assistant? or Node red? 
I have install it from terminal. but can not fin out the rest. 
I used pip install yalesmartalarmclient. 

best regard
Kourosh

**Comment by domwillcode** [comment]
Hi Kourosh 

You can use it straight out of the box in home assistant.

Take a look at the HA documentation: https://www.home-assistant.io/integrations/yale_smart_alarm/

**Comment by Marmoulak** [comment]
Thanks for your answer, I already install yale_smart_alarm but Trigger alarm panic button is not listed in attributes.

**Comment by gjohansson-ST** [comment]
That's on the to-do list to integrate it into HA directly.
You can of course write your own py scripts and run them locally in HA/NR if you prefer.

**Comment by gjohansson-ST** [comment]
Trigger panic button is part of the new HA release on Wednesday

**Comment by Marmoulak** [comment]
Perfect, Nice work @gjohansson-ST
