### ISSUE TITLE
Expose type hints

### ISSUE THREAD

**Issue by epenet** [domwillcode/yale-smart-alarm-client#53]
Hi,
Because the source doesn't contain `py.typed` file, the type hints are not exposed outside of the project.
I suggest that you include it in the next release.

See:
- PEP: https://peps.python.org/pep-0561
- Sample: https://github.com/hacf-fr/sfrbox-api/blob/main/src/sfrbox_api/py.typed

Spotted in https://github.com/home-assistant/core/pull/85603

**Comment by gjohansson-ST** [comment]
Is included
