### ISSUE TITLE
Yale Smart Living - Fire/Smoke detector temperature sensor and water leak sensor data - enhancement request

### ISSUE THREAD

**Issue by Vladdy65** [domwillcode/yale-smart-alarm-client#55]
Enhancement Request

In an effort to leverage existing sensors, and the fact that their data is available in the native Yale Alarm app, combined with a naive presumption that if the app is accessing this data the API might have access to it too, I propose the following enhancement requests: 

Addition of Fire/Smoke detector temperature sensor - these are available on the native Yale app under the  'Control' option.
Addition of Water sensors - these are available as binary sensors on the native Yale app.

**Comment by gjohansson-ST** [comment]
From the integration download a diagnostics file and attach it to this issue so I can see how it looks. Thanks 👍

**Comment by Vladdy65** [comment]
Herewith attached diagnostics file as requested.
[config_entry-yale_smart_alarm-0eec53a6042fe0586040bb7c49a1b487.json](https://github.com/domwillcode/yale-smart-alarm-client/files/14322922/config_entry-yale_smart_alarm-0eec53a6042fe0586040bb7c49a1b487.json)

**Comment by gjohansson-ST** [comment]
So I had a look and regarding the temp sensors those can be added easily which I'll look at shortly.

For both smoke and water it's not reporting a status (clear or something) so actually to add those in, in the form off binary sensors to see if they have tripped or not I need you to trip them (water on the water sensor).
Then wait a cycle for the integration to update and then download and paste a new diagnostics file so I can understand if it's actually telling a state when tripping or not.
I think perhaps putting water on the water sensor is the first step than making a small fire 🤣

**Comment by Vladdy65** [comment]
ETA next week as travelling.

**Comment by Vladdy65** [comment]
Herewith file (...water_sensor) with water_sensor activated several times but downloaded after the fact. Activated for a second or two then stuck it in a glass of wate for ~20min, and again for a second or so. From what I understand of this, in History, event_type: 1154 is received when activated and 3154 when deactivated. Timings agree with what the Yale app reflects.
[config_entry-yale_smart_alarm-0eec53a6042fe0586040bb7c49a1b487 (water_sensor).json](https://github.com/domwillcode/yale-smart-alarm-client/files/14546715/config_entry-yale_smart_alarm-0eec53a6042fe0586040bb7c49a1b487.water_sensor.json)

**Comment by Vladdy65** [comment]
Herewith file (...activated) with water_sensor in glass of water taken during event. As the alarm went off I had to acknowledge this and silence it. So not sure if this had any impact on the device_status, but I do not see any change in the reported device status, only the History event list.
[config_entry-yale_smart_alarm-0eec53a6042fe0586040bb7c49a1b487 (activated).json](https://github.com/domwillcode/yale-smart-alarm-client/files/14546746/config_entry-yale_smart_alarm-0eec53a6042fe0586040bb7c49a1b487.activated.json).
As regards the temperatures, the device_status, status_temp: 21 agrees with what the Yale app reports, but there seem to be no events pushed through when this changes from what I can establish. I have seen it change on the Yale app, and the change is reflected in the device_status.
Fire alarm activation to follow.
