### ISSUE TITLE
Timeout for Yale endpoint

### ISSUE THREAD

**Issue by WattageGuy** [domwillcode/yale-smart-alarm-client#70]
My request is successful but I still get a timeout error. Any idea why?

Traceback (most recent call last):
  File "/python/Yale/yale_auto_lock-off.py", line 13, in <module>
    print(lock.set_autolock(False))
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/lib/python3.11/site-packages/yalesmartalarmclient/lock.py", line 213, in set_autolock
    return self._lock_api.set_autolock(lock=self, autolock=autolock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/lib/python3.11/site-packages/yalesmartalarmclient/lock.py", line 440, in set_autolock
    operation_status = self.auth.post_authenticated(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.local/lib/python3.11/site-packages/yalesmartalarmclient/auth.py", line 121, in post_authenticated
    raise ConnectionError(f"Connection error {error}") from error
requests.exceptions.ConnectionError: Connection error 504 Server Error: Gateway Timeout for url: https://mob.yalehomesystem.co.uk/yapi/api/minigw/lock/config/

**Comment by gjohansson-ST** [comment]
You mean you always get it for this particular method to set autolock or more in general?

In a more general manner it's been like that for a long time and very often end with a client error even if the method as such succeeds without problem. No idea why but I would assume their api is quite flaky.

**Comment by WattageGuy** [comment]
Okay sad that they have such a bad api. I only use the API for this so I don't know if it happens on other methods. But I also get this error in home assistant every time I unlock or lock my Yale doorman. Is it possible to retrieve if auto lock is on or off with any method?
