### ISSUE TITLE
Does it need to be a package?

### ISSUE THREAD

**Issue by charlesastaylor** [domwillcode/yale-smart-alarm-client#9]
(Sorry for all the notifications I'm going to have given you!)

Seems like would all fit in a module yalesmartalarmclient.py nicely.

**Comment by domwillcode** [comment]
(No worries, the contributions are much appreciated!)

It does! I confess, I'm not a Python guy :face_with_head_bandage: . I'll look into turning it into a module with the next major change to HA.

**Comment by charlesastaylor** [comment]
(Well you're more than welcome then!)

Well if you want any help let me know! Should be pretty straight forward, downside will be it'll break the way importing the client is currently done.
